name: pilar_presence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  firebase_core: 2.12.0
  firebase_auth: 4.6.0
  cloud_firestore: 4.7.0
  image_picker: 0.8.6
  firebase_storage: 11.2.0
  bottom_bar: 2.0.2
  google_fonts: 4.0.4
  ionicons: 0.2.1
  geolocator: 9.0.2
  dropdown_search: 5.0.3
  flutter_map: 3.0.0
  latlong2: 0.8.1
  open_street_map_search_and_pick: 0.0.15
  cached_network_image: 3.2.3
  sliding_up_panel: 2.0.0+1
  geocoding: 2.0.5
  timezone: 0.9.0
  image_cropper: 3.0.1
  flutter_image_compress: 1.1.3
  path_provider: 2.0.11
  qr_code_scanner: 1.0.1
  flutter_screenutil: 5.8.1
  syncfusion_flutter_datepicker: 20.3.60
  firebase_messaging: 14.6.0
  flutter_local_notifications: 13.0.0
  deep_collection: 1.0.2
  connectivity_plus: 3.0.2
  internet_connection_checker: ^1.0.0+1
  flutter_datetime_picker: 1.5.1
  sizer: 2.0.15
  nanoid: 1.0.0
  flutter_slidable: 3.0.0
  photo_view: 0.14.0
  change_case: 1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

