part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const MY_PAGE_VIEW = _Paths.MY_PAGE_VIEW;
  static const LOGIN = _Paths.LOGIN;
  static const USER_PROFILE = _Paths.USER_PROFILE;
  static const PRESENCE_REMOTE = _Paths.PRESENCE_REMOTE;
  static const USER_ADD = _Paths.USER_ADD;
  static const USER_UPDATE_PROFILE = _Paths.USER_UPDATE_PROFILE;
  static const USER_UPDATE_EMAIL = _Paths.USER_UPDATE_EMAIL;
  static const USER_UPDATE_PASSWORD = _Paths.USER_UPDATE_PASSWORD;
  static const PRESENCE_HISTORY = _Paths.PRESENCE_HISTORY;
  static const ANNOUNCEMENT = _Paths.ANNOUNCEMENT;
  static const PRESENCE_DETAIL = _Paths.PRESENCE_DETAIL;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const NEW_PASSWORD = _Paths.NEW_PASSWORD;
  static const MAP = _Paths.MAP;
  static const ADMIN_MENU = _Paths.ADMIN_MENU;
  static const PERIZINAN_REQUEST = _Paths.PERIZINAN_REQUEST;
  static const CUTI_TAHUNAN = _Paths.CUTI_TAHUNAN;
  static const OVERTIME = _Paths.OVERTIME;
  static const OVERTIME_DETAIL = _Paths.OVERTIME_DETAIL;
  static const OVERTIME_REQUEST = _Paths.OVERTIME_REQUEST;
  static const OVERTIME_HISTORY = _Paths.OVERTIME_HISTORY;
  static const PERIZINAN_CUTI = _Paths.PERIZINAN_CUTI;
  static const PERIZINAN_CUTI_REQUEST = _Paths.PERIZINAN_CUTI_REQUEST;
  static const PERIZINAN_SAKIT = _Paths.PERIZINAN_SAKIT;
  static const PERIZINAN_SAKIT_REQUEST = _Paths.PERIZINAN_SAKIT_REQUEST;
  static const CUTI_TAHUNAN_ADD = _Paths.CUTI_TAHUNAN_ADD;
  static const MANAGEMENT_USER = _Paths.MANAGEMENT_USER;
  static const MONITORING = _Paths.MONITORING;
  static const MANAGEMENT_ANNOUNCEMENT = _Paths.MANAGEMENT_ANNOUNCEMENT;
  static const REPORT = _Paths.REPORT;
  static const ACCOUNT_VALIDATION = _Paths.ACCOUNT_VALIDATION;
  static const PENGUMUMAN_ADD = _Paths.PENGUMUMAN_ADD;
  static const ANNOUNCEMENT_ADD = _Paths.ANNOUNCEMENT_ADD;
  static const PHOTO_VIEW = _Paths.PHOTO_VIEW;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const MY_PAGE_VIEW = '/my-page-view';
  static const LOGIN = '/login';
  static const USER_PROFILE = '/user-profile';
  static const PRESENCE_REMOTE = '/presence-remote';
  static const USER_ADD = '/user-add';
  static const USER_UPDATE_PROFILE = '/user-update-profile';
  static const USER_UPDATE_EMAIL = '/user-update-email';
  static const USER_UPDATE_PASSWORD = '/user-update-password';
  static const PRESENCE_HISTORY = '/presence-history';
  static const ANNOUNCEMENT = '/announcement';
  static const PRESENCE_DETAIL = '/presence-detail';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const NEW_PASSWORD = '/new-password';
  static const MAP = '/map';
  static const ADMIN_MENU = '/admin-menu';
  static const PERIZINAN_REQUEST = '/perizinan-request';
  static const CUTI_TAHUNAN = '/cuti-tahunan';
  static const OVERTIME = '/overtime';
  static const OVERTIME_DETAIL = '/overtime-detail';
  static const OVERTIME_REQUEST = '/overtime-request';
  static const OVERTIME_HISTORY = '/overtime-history';
  static const PERIZINAN_CUTI = '/perizinan-cuti';
  static const PERIZINAN_CUTI_REQUEST = '/perizinan-cuti-request';
  static const PERIZINAN_SAKIT = '/perizinan-sakit';
  static const PERIZINAN_SAKIT_REQUEST = '/perizinan-sakit-request';
  static const CUTI_TAHUNAN_ADD = '/cuti-tahunan-add';
  static const MANAGEMENT_USER = '/management-user';
  static const MONITORING = '/monitoring';
  static const MANAGEMENT_ANNOUNCEMENT = '/management-announcement';
  static const REPORT = '/report';
  static const ACCOUNT_VALIDATION = '/account-validation';
  static const PENGUMUMAN_ADD = '/pengumuman-add';
  static const ANNOUNCEMENT_ADD = '/announcement-add';
  static const PHOTO_VIEW = '/photo-view';
}
